package edu.ncsu.github;

import javax.swing.*;
import java.awt.*;

public class OutputGUI extends JFrame {

	private static OutputGUI instance;

	public static OutputGUI getInstance() {
		if (instance == null) {
			instance = new OutputGUI();
		}
		return instance;
	}

	private OutputGUI() {

	}

	/**
	 * Displays the main Wordle Solver GUI.
	 */
	public void display() {
		try {
			// Set the look and feel to Windows
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
				 UnsupportedLookAndFeelException e) {
			// Print error message if look and feel setting fails
			System.out.println("Error while setting GUI look and feel: " + e);
		}

		setTitle("Output");
		setContentPane(mainPanel);
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		pack();
		setSize(getWidth(), 600);
		setLocationRelativeTo(null);
		setVisible(true);
	}

	public void addToOutput(String str) {
		textPane.setText(textPane.getText() + str);
	}

	public void addToOutput(char c) {
		addToOutput(String.valueOf(c));
	}

	public void clearOutput() {
		textPane.setText("");
	}

	private JTextPane textPane;
	private JPanel mainPanel;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		mainPanel = new JPanel();
		mainPanel.setLayout(new GridBagLayout());
		final JScrollPane scrollPane1 = new JScrollPane();
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.weightx = 1.0;
		gbc.weighty = 1.0;
		gbc.fill = GridBagConstraints.BOTH;
		mainPanel.add(scrollPane1, gbc);
		textPane = new JTextPane();
		textPane.setEditable(false);
		scrollPane1.setViewportView(textPane);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return mainPanel;
	}

}
